export const APP_SET_ERRORS = "APP_SET_ERRORS";
export const APP_SET_LOADING = "APP_SET_LOADING";
export const APP_SET_PAGE_STATE = "APP_SET_PAGE_STATE";
export const APP_SET_ART_PIECES_LIST = "APP_SET_ART_PIECES_LIST";
export const APP_HANDLE_FAVORITES = "APP_ADD_FAVORITE";
export const APP_SET_FAVORITES = "APP_SET_FAVORITES";
export const APP_SET_FAVORITE_ART_PIECES = "APP_SET_FAVORITE_ART_PIECES";
